# Generated by Django 4.1 on 2022-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=240, verbose_name='Name')),
                ('member1', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email1', models.EmailField(default='', max_length=254)),
                ('member2', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email2', models.EmailField(default='', max_length=254)),
                ('member3', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email3', models.EmailField(default='', max_length=254)),
                ('member4', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email4', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
