# Generated by Django 4.1 on 2022-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap22', '0002_team_phone_alter_team_email2_alter_team_email3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.CharField(default='', max_length=240, verbose_name='Contact')),
                ('firm', models.CharField(default='', max_length=240, verbose_name='Firm')),
                ('desig', models.CharField(default='', max_length=240, verbose_name='Designation')),
            ],
        ),
    ]
