# Generated by Django 4.1 on 2022-10-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap22', '0003_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=240, verbose_name='Name')),
                ('sector', models.CharField(max_length=240, verbose_name='Sector')),
                ('q1', models.CharField(default='', max_length=2000, verbose_name='What problem is your team trying to solve and what solution do you propose? ')),
                ('q2', models.CharField(default='', max_length=2000, verbose_name='Who are the major stakeholders (key partners) in your startup? ')),
                ('q3', models.CharField(default='', max_length=2000, verbose_name='Who are your major customer segments? ')),
                ('q4', models.CharField(default='', max_length=2000, verbose_name='Describe your market share through TAM, SAM, SOM.  ')),
                ('q5', models.CharField(default='', max_length=2000, verbose_name='What is a unique value proposition that your startup builds upon?  ')),
                ('q6', models.CharField(default='', max_length=2000, verbose_name='What is your business model for your startup? How are you generating revenue?  ')),
                ('q7', models.CharField(default='', max_length=2000, verbose_name='Are there any competitors working on the same project?  If yes , mention how you are better than them.')),
                ('q8', models.CharField(default='', max_length=2000, verbose_name='Are you full time working on your startup or partial?  ')),
            ],
        ),
    ]
