# Generated by Django 4.1 on 2022-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap22', '0004_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='q1',
            field=models.CharField(default='', max_length=5000, verbose_name='What problem is your team trying to solve and what solution do you propose? '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q2',
            field=models.CharField(default='', max_length=5000, verbose_name='Who are the major stakeholders (key partners) in your startup? '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q3',
            field=models.CharField(default='', max_length=5000, verbose_name='Who are your major customer segments? '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q4',
            field=models.CharField(default='', max_length=5000, verbose_name='Describe your market share through TAM, SAM, SOM.  '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q5',
            field=models.CharField(default='', max_length=5000, verbose_name='What is a unique value proposition that your startup builds upon?  '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q6',
            field=models.CharField(default='', max_length=5000, verbose_name='What is your business model for your startup? How are you generating revenue?  '),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q7',
            field=models.CharField(default='', max_length=5000, verbose_name='Are there any competitors working on the same project?  If yes , mention how you are better than them.'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='q8',
            field=models.CharField(default='', max_length=5000, verbose_name='Are you full time working on your startup or partial?  '),
        ),
    ]
