# Generated by Django 4.1 on 2022-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap22', '0005_alter_playbook_q1_alter_playbook_q2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='D2c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=240, verbose_name='Name')),
                ('phone', models.CharField(default='', max_length=200)),
                ('member1', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email1', models.EmailField(default='', max_length=254)),
                ('member2', models.CharField(blank=True, default='', max_length=240, verbose_name='Name')),
                ('email2', models.EmailField(blank=True, default='', max_length=254)),
                ('member3', models.CharField(blank=True, default='', max_length=240, verbose_name='Name')),
                ('email3', models.EmailField(blank=True, default='', max_length=254)),
                ('member4', models.CharField(blank=True, default='', max_length=240, verbose_name='Name')),
                ('email4', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
    ]
