# Generated by Django 3.2.7 on 2022-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('sop', models.CharField(max_length=2000)),
            ],
        ),
    ]
