# Generated by Django 3.2.7 on 2022-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('rank', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=200)),
            ],
        ),
    ]
