# Generated by Django 3.2.7 on 2022-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0011_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=200)),
                ('member2', models.CharField(max_length=200)),
                ('member3', models.CharField(max_length=200)),
                ('member4', models.CharField(max_length=200)),
            ],
        ),
    ]
