# Generated by Django 3.2.7 on 2022-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0014_auto_20220627_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
