# Generated by Django 3.2.7 on 2022-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0015_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sender_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='status2',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='team',
            name='status3',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='team',
            name='status4',
            field=models.BooleanField(default='False'),
        ),
    ]
