# Generated by Django 3.2.7 on 2022-06-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0017_rename_status_team_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status4',
        ),
    ]
