# Generated by Django 3.2.7 on 2022-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0018_auto_20220628_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teampoint',
            field=models.IntegerField(default='0'),
        ),
    ]
