# Generated by Django 3.2.7 on 2022-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0019_team_teampoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sender_cr_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
