# Generated by Django 3.2.7 on 2022-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0020_invite_sender_cr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='proof',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
