# Generated by Django 3.2.7 on 2022-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0021_team_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_team',
            field=models.BooleanField(default='False'),
        ),
    ]
