# Generated by Django 3.2.7 on 2022-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0022_userprofile_in_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='task_status',
            field=models.BooleanField(default='False'),
        ),
    ]
