# Generated by Django 3.2.7 on 2022-07-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0023_team_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='task_status',
            new_name='task1_status',
        ),
    ]
