# Generated by Django 3.2.7 on 2022-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0024_rename_task_status_team_task1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ref',
            field=models.CharField(default='', max_length=200),
        ),
    ]
