# Generated by Django 3.2.7 on 2022-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0026_userprofile_bonus_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crid', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=5000)),
            ],
        ),
    ]
