# Generated by Django 3.2.7 on 2022-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0027_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='decline',
            field=models.BooleanField(default='False'),
        ),
    ]
