# Generated by Django 4.1 on 2022-08-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0028_invite_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proof',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
