# Generated by Django 4.1 on 2022-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0029_userprofile_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='task1_status',
            field=models.BooleanField(default='False'),
        ),
    ]
