# Generated by Django 4.1 on 2022-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0030_userprofile_task1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refer_count',
            field=models.IntegerField(default='0'),
        ),
    ]
