# Generated by Django 4.1 on 2022-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0031_userprofile_refer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
