# Generated by Django 4.1 on 2023-06-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0035_userprofile_proof3_userprofile_proof4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='in_team',
            new_name='inteam',
        ),
    ]
