# Generated by Django 4.1 on 2023-06-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0036_rename_in_team_userprofile_inteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='inteam',
            new_name='in_team',
        ),
    ]
