# Generated by Django 4.1 on 2024-07-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0038_userprofile_is_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'state', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr_portal.college')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='proof4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='refer_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sop',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task1_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task2_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task3_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='task4_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='in_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cr_portal.college'),
        ),
    ]
