# Generated by Django 4.1 on 2024-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr_portal', '0039_college_student_delete_blog_delete_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
