# Generated by Django 4.1 on 2023-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.CharField(default='', max_length=240, verbose_name='Contact')),
                ('school', models.CharField(default='', max_length=240, verbose_name='Institute')),
                ('age', models.PositiveIntegerField(default='', verbose_name='Age')),
                ('sdw', models.BooleanField(default=False, verbose_name='Self Defence Workshop')),
                ('csr', models.BooleanField(default=False, verbose_name='CSR Fest')),
                ('sebi', models.BooleanField(default=False, verbose_name='SEBI')),
                ('cyber', models.BooleanField(default=False, verbose_name='Cybercrime')),
                ('health', models.BooleanField(default=False, verbose_name='Health Checkup')),
                ('sociotech', models.BooleanField(default=False, verbose_name='Socio tech')),
                ('coc', models.BooleanField(default=False, verbose_name='Concert')),
                ('menstrual', models.BooleanField(default=False, verbose_name='Menstrual')),
                ('csrm', models.BooleanField(default=False, verbose_name='Csr Modelling')),
                ('sspe', models.BooleanField(default=False, verbose_name='small scale')),
                ('rap', models.BooleanField(default=False, verbose_name='Rap Battle')),
                ('Media', models.BooleanField(default=False, verbose_name='Media Conclave')),
                ('eq', models.BooleanField(default=False, verbose_name='EQ')),
                ('theatre', models.BooleanField(default=False, verbose_name='Theatre Play')),
                ('manual', models.BooleanField(default=False, verbose_name='Manual')),
                ('menheal', models.BooleanField(default=False, verbose_name="Men's Health")),
                ('samwaad', models.BooleanField(default=False, verbose_name='Samwaad')),
            ],
        ),
    ]
