# Generated by Django 4.1 on 2023-01-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('imgurl', models.CharField(max_length=1000, verbose_name='Image Url')),
                ('type', models.CharField(max_length=240, verbose_name='Type')),
            ],
        ),
    ]
