# Generated by Django 4.1 on 2023-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0003_remove_normaluser_age_remove_normaluser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(default='', max_length=240, verbose_name='Tag'),
        ),
    ]
