# Generated by Django 4.1 on 2023-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0005_normaluser_cpr_normaluser_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='csr',
            field=models.BooleanField(default=False, verbose_name='CSR'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='csrm',
            field=models.BooleanField(default=False, verbose_name='CSR Modelling'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='cyber',
            field=models.BooleanField(default=False, verbose_name='Cyber'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='MANUAL Scavanging'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='sdw',
            field=models.BooleanField(default=False, verbose_name='Self Defence'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='sociotech',
            field=models.BooleanField(default=False, verbose_name='Socio Tech'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='sspe',
            field=models.BooleanField(default=False, verbose_name='Small Scale'),
        ),
    ]
