# Generated by Django 4.1 on 2023-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0006_alter_normaluser_csr_alter_normaluser_csrm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='Ano',
            field=models.CharField(default='', max_length=240, verbose_name='Ticket No.'),
        ),
    ]
