# Generated by Django 4.1 on 2023-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0007_normaluser_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='block',
            field=models.BooleanField(default=False, verbose_name='Blockchain Sustainibility'),
        ),
    ]
