# Generated by Django 4.1 on 2023-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0008_normaluser_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='menheal',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='Disability'),
        ),
    ]
