# Generated by Django 4.1 on 2023-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0010_normaluser_mental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='csrm',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='csrc',
            field=models.BooleanField(default=False, verbose_name='CSR Conclave'),
        ),
    ]
