# Generated by Django 4.1 on 2023-01-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0011_remove_normaluser_csrm_normaluser_csrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.CharField(default='', max_length=240, verbose_name='Ticket No.')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.CharField(default='', max_length=240, verbose_name='Contact')),
            ],
        ),
    ]
