# Generated by Django 4.1 on 2022-12-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.CharField(default='', max_length=240, verbose_name='Contact')),
                ('school', models.CharField(default='', max_length=240, verbose_name='Institute')),
                ('age', models.PositiveIntegerField(default='', max_length=240, verbose_name='Age')),
            ],
        ),
    ]
