# Generated by Django 4.1 on 2022-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='age',
            field=models.PositiveIntegerField(default='', verbose_name='Age'),
        ),
    ]
